# Installed by icons-feather — discovered as /usr/share/iconlibutils/library/feather/
name=feather
type=auto
path=/usr/share/icons-feather
title=feather
license=MIT
homepage=https://feathericons.com/
description=Feather Icons
package=icons-feather
